# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc_test_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
